### ISSUE TITLE
Could not find part of path

### ISSUE THREAD

**Issue by oldhighrise** [Quackster/Elias#9]
=============Error Logging ===========
System.IO.DirectoryNotFoundException occurred when processing furni: rare_blackrosegold_barrier
Date: 4/22/2024 8:19:56 PM
Error Message: Could not find a part of the path 'C:\Users\ricky\OneDrive\Desktop\Elias-v0.4\EliasConverter\temp\binaryData'.
Stack Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Elias.Utilities.BinaryDataUtil.SolveFile(Elias elias, String outputDirectory, String fileNameContains) in C:\Users\Alex\Documents\GitHub\Elias\Elias\Utilities\BinaryDataUtil.cs:line 17
   at EliasLibrary.Elias.GenerateAliases(Boolean isDownscaled) in C:\Users\Alex\Documents\GitHub\Elias\Elias\Elias.cs:line 433
   at EliasLibrary.Elias.Parse() in C:\Users\Alex\Documents\GitHub\Elias\Elias\Elias.cs:line 84
   at EliasApp.Program.ConvertFile(String file, String ffdecPath, String directorPath, String cctPath) in C:\Users\Alex\Documents\GitHub\Elias\EliasApp\Program.cs:line 352

**Comment by Quackster** [comment]
Can you attach the file you are using?

**Comment by oldhighrise** [comment]
I had used the habbo-downloader (https://github.com/Quackster/habbo-downloader) and got all files needed and the swfs. this is my furnidata, just put in in .txt to share, it's xml.
and this is the swf im using. Using v0.4
[furnidata.txt](https://github.com/Quackster/Elias/files/15083949/furnidata.txt)
https://www.mediafire.com/file/qppengmdpbkabfj/rare_blackrosegold_barrier.swf/file

**Comment by Quackster** [comment]
The same .SWF worked fine for me. 

It's likely you don't have JPEXS installed, or you didn't set the path to its ffdec.exe executable correctly.

![image](https://github.com/Quackster/Elias/assets/1328523/1a968cce-0652-4713-a6c6-888770c5145f)

**Comment by oldhighrise** [comment]
Pretty sure everything is set up correctly

![1](https://github.com/Quackster/Elias/assets/166974629/1e14e653-dacf-43b8-943a-50279b306318)

config
 `<configuration>
   <ffdec>C:\Program Files (x86)\FFDec\ffdec.exe</ffdec>
   <converter_app>C:\Users\ricky\OneDrive\Desktop\Elias-v0.4\EliasConverter\EliasConverter.exe</converter_app>
   <output_path>C:\Users\ricky\OneDrive\Desktop\Elias-v0.4\SWFs</output_path>
   <furnidata_path>C:\Users\ricky\OneDrive\Desktop\Elias-v0.4\furnidata.xml</furnidata_path>
   <small_furni>
      <generate>true</generate>
      <generate_modern>true</generate_modern>
   </small_furni>
   <options>
      <save_as_cst>false</save_as_cst>
      <emergency_fix>false</emergency_fix>
      <close_when_finished>false</close_when_finished>
   </options>
</configuration>`

When i run the program it goes to open JPEXS but close then throws that error and just repeats.
also using JPEXS 20.1.0

**Comment by Quackster** [comment]
Yeah, you're using too recent a version of JPEXS. 

Fixed: https://github.com/Quackster/Elias/releases/tag/v0.5
